---
layout: cv
title: Kaliah Walton CV
---
# Kaliah Walton
Student, Data Analyst, Computer Engineer.

<div id="kaliahwaltonn@gmail.com">

## Currently
A student at Brigham Young University_Idaho, Majoring in Computer Engineering with a minor in World History.

### Specialized in

Data Visualization, Data Analysis, programming


### Research interests

Hardware of computers, Machine Learning, Data Visualization


## Education

`2020-2022`
__Mesa Community College__

`2024 - 2025`
__Brigham Young Univeristy-Idaho__

- Bachelors in Computer Engineering


## Occupation
`2016-2020`
__Fast Track Legal__, Mesa AZ

-Postal Locate Coordinater

`2021`
__Dutch Bros LLC__, Mesa AZ, Idaho Falls ID

- Broista '2021-2022'
- Mobster (Traveling Trainer) '2022- current'

## Skills
- Rapid adaptability to new environments
- Proficient in training individuals within fast-paced settings
- Exceptional interpersonal skills, adept at effectively communicating and motivating others
- Versed in Tableau, SQL, Python, and Plotly


Last updated: April 2024 -->